// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXusFqApJyVw7f_OCmmr65SGJZn_1RcIk',
    appId: '1:474301632018:web:48863e991b8d6763f412cb',
    messagingSenderId: '474301632018',
    projectId: 'firestoretodo-7a759',
    authDomain: 'firestoretodo-7a759.firebaseapp.com',
    storageBucket: 'firestoretodo-7a759.appspot.com',
    measurementId: 'G-3QJRRFTQ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1iBAU-dAPGMehl84wCU1oXkKXspl-oNA',
    appId: '1:474301632018:android:96f515d689827828f412cb',
    messagingSenderId: '474301632018',
    projectId: 'firestoretodo-7a759',
    storageBucket: 'firestoretodo-7a759.appspot.com',
  );
}
